apiVersion: apps/v1
kind: Deployment
metadata:
  name: idgen-app
  namespace: id-gen
  labels:
    app: idgen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idgen-app
  template:
    metadata:
      labels:
        app: idgen-app
    spec:
      containers:
        - name: idgen-app
          resources: 
          image: devbarbea/idgen:1.1
          ports:
            - containerPort: 80
          env:
            - name: MONGO_URL
              value: mongodb-service:27017

---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: id-gen
spec:
  selector:
    app: idgen-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30103
