---
apiVersion: v1
kind: Namespace
metadata:
  name: sock-shop
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongoex-configmap
  namespace: id-gen
data:
  database_url: mongodb-service
