apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: easyk8s-cluster
  region: us-east-1
nodeGroups:
  - name: worker-group
    instanceType: t3.medium
    desiredCapacity: 3
    minSize: 3
    maxSize: 4